version: 2

models:

  - name: stg_stock_price
    description: "Cleaned staging view for AMZN/META stock prices"
    columns:
      - name: symbol
        description: "Ticker (AMZN, META)"
        tests: [not_null]
      - name: date
        description: "Trading date"
        tests: [not_null]
      - name: close
        description: "Closing price"
        tests: [not_null]
      - name: volume
        description: "Daily trading volume"
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: [symbol, date]

  - name: stock_transformations
    description: "Intermediate features-SMA 20/50/200, Momentum(10), RSI(14)"
    columns:
      - name: symbol
        tests: [not_null]
      - name: date
        tests: [not_null]
      - name: sma_20
        description: "20-day SMA"
      - name: sma_50
        description: "50-day SMA"
      - name: sma_200
        description: "200-day SMA"
      - name: momentum_10
        description: "Close - close_lag_10"
      - name: rsi_14
        description: "14-day RSI (rolling avg)"

  - name: stock_price_technical_indicators
    description: "Final table"
    columns:
      - name: symbol
        tests: [not_null]
      - name: date
        tests: [not_null]
      - name: trade_signal
        description: "Our recommendation to buy, sell, hold"







